version: "3.7"
services:

  laravel:
    build:
      context: ./_php
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./_laravel:/var/www
    networks:
      - laravel-bridge

  db:
    image: mariadb:latest
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_PASSWORD: docker
      MYSQL_USER: docker
    ports:
      - 3306:3306
    volumes:
      - ./_db:/docker-entrypoint-initdb.d
      - laravel-db-volume:/var/lib/mysql
    networks:
      - laravel-bridge

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./_laravel:/var/www
      - ./_nginx:/etc/nginx/conf.d/
    networks:
      - laravel-bridge

networks:
  laravel-bridge:
    driver: bridge

volumes:
  laravel-db-volume: